### ISSUE TITLE
Type checking sometimes hangs

### ISSUE THREAD

**Issue by TomerAberbach** [dubzzz/ava-fast-check#14]
I've been writing tests with `ava-fast-check` and I think I've noticed an interesting type checking issue (it might be a problem with TypeScript). I can consistently get type checking to hang (i.e. go into an infinite loop) and make my IDE freeze for a good few seconds by writing the following code and hovering my mouse over the array, which is where the type error is:

```js
const arb = () => fc.constantFrom(...[1, 2, 3])
testProp(
  `test`,
  [arb().chain(value => fc.constant(value))],
  () => {}
)
```

![image](https://user-images.githubusercontent.com/23299544/95805425-63fba100-0cd3-11eb-8f56-8de94c11feb0.png)

Interestingly, the error goes away if you inline the `arb` function. As I said before, this is probably an issue with TypeScript because the type checker should never go into an infinite loop (although I have read in the past that TypeScript's type system is Turing-complete, which means that type checking is undecidable), but I wonder if there's anything we can change about the type definition of `testProp` to make TypeScript fail quickly or accept these arguments.

**Comment by TomerAberbach** [comment]
Looks like this snippet of code no longer hangs! (probably due to the recent type changes)

**Comment by dubzzz** [comment]
Oups, I never investigated this one. So sorry. Meanwhile I may add it into my local test suite based on typings just in case

**Comment by TomerAberbach** [comment]
No worries! Good idea to add tests 😄

**Comment by dubzzz** [comment]
I added a simple one in fast-check itself - https://github.com/dubzzz/fast-check/pull/1380

For the moment, I have no real tests for types on ava-fast-check. Not yet 👍
